export interface PortfolioItem {
    id: string
    title: string
    category: string
    type: "image" | "video"
    thumbnail: string
    year: string
    description: string
    client?: string
    images: string[]
    aspectRatio: "landscape" | "portrait" | "square"
  }

  export const portfolioItems: PortfolioItem[] = [
    {
      id: "24",
      title: "Double-flowered",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-lsy-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/ordinary-lsy-main.jpg",
        "/images/ordinary-lsy-sub1.jpg",
        "/images/ordinary-lsy-sub2.jpg",
      ],
    },
    {
      id: "11",
      title: "Autumn",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-syh2-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "landscape",
      images: [
        "/images/ordinary-syh2-main.jpg",
        "/images/ordinary-syh2-sub1.jpg",
        "/images/ordinary-syh2-sub2.jpg",
      ],
    },
    {
      id: "37",
      title: "DDP",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-cyj2-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-cyj2-main.jpg",
        "/images/rostro-cyj2-sub1.jpg",
        "/images/rostro-cyj2-sub2.jpg",
        "/images/rostro-cyj2-sub3.jpg",
        "/images/rostro-cyj2-sub4.jpg",
        "/images/rostro-cyj2-sub5.jpg",
        "/images/rostro-cyj2-sub6.jpg",
      ],
    },
    {
      id: "15",
      title: "Spartan I",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-sgg-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-sgg-main.jpg",
        "/images/rostro-sgg-sub1.jpg",
      ],
    },
    {
      id: "35",
      title: "Spartan III",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-spt-main.jpg",
      year: "2024",
      description: "",
      aspectRatio: "landscape",
      images: [
        "/images/rostro-spt-main.jpg",
        "/images/rostro-spt-sub1.jpg",
        "/images/rostro-spt-sub2.jpg",
      ],
    },
    {
      id: "3",
      title: "Peak",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-syh-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-syh-main.jpg",
        "/images/rostro-syh-sub1.jpg",
        "/images/rostro-syh-sub2.jpg",
      ],
    },
    {
      id: "17",
      title: "Flow III",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-sss-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-sss-main.jpg",
        "/images/athletic-sss-sub1.jpg",
        "/images/athletic-sss-sub2.jpg",
      ],
    },
    {
      id: "16",
      title: "Flow II",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-lgr-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-lgr-main.jpg",
        "/images/athletic-lgr-sub1.jpg",
      ],
    },
    {
      id: "23",
      title: "Flow IV",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-fff-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-fff-main.jpg",
      ],
    },
    {
      id: "18",
      title: "Movement I",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-csw-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-csw-main.jpg",
        "/images/athletic-csw-sub1.jpg",
      ],
    },
    {
      id: "19",
      title: "Movement II",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-hyg-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-hyg-main.jpg",
        "/images/athletic-hyg-sub1.jpg",
      ],
    },
    {
      id: "20",
      title: "Movement III",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-kdh-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-kdh-main.jpg",
      ],
    },
    {
      id: "25",
      title: "Summer III",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-ceg-main.jpg",
      year: "2023",
      description: "",
      aspectRatio: "landscape",
      images: [
        "/images/ordinary-ceg-main.jpg",
      ],
    },
    {
      id: "26",
      title: "Summer IV",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-lgr-main.jpg",
      year: "2023",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/ordinary-lgr-main.jpg",
      ],
    },
    {
      id: "2",
      title: "Immersion",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-ksy-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-ksy-main.jpg",
        "/images/rostro-ksy-sub1.jpg",
      ],
    },
    {
      id: "29",
      title: "Summer I",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-kyb-main.jpg",
      year: "2023",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-kyb-main.jpg",
        "/images/rostro-kyb-sub1.jpg",
        "/images/rostro-kyb-sub2.jpg",
      ],
    },
    {
      id: "30",
      title: "Spartan II",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-ljy-main.jpg",
      year: "2024",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-ljy-main.jpg",
        "/images/rostro-ljy-sub2.jpg",
      ],
    },
    {
      id: "31",
      title: "Flow V",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-ccc-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-ccc-main.jpg",
        "/images/athletic-ccc-sub1.jpg",
        "/images/athletic-ccc-sub2.jpg",
      ],
    },
    {
      id: "32",
      title: "Flow VI",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-mmm-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/athletic-mmm-main.jpg",
        "/images/athletic-mmm-sub1.jpg",
        "/images/athletic-mmm-sub2.jpg",
      ],
    },
    {
      id: "12",
      title: "Swim",
      category: "athletic",
      type: "image",
      thumbnail: "/images/athletic-aaa-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "landscape",
      images: [
        "/images/athletic-aaa-main.jpg",
        "/images/athletic-aaa-sub1.jpg",
        "/images/athletic-aaa-sub2.jpg",
      ],
    },
    {
      id: "33",
      title: "Glorious",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-csd-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "landscape",
      images: [
        "/images/ordinary-csd-main.jpg",
        "/images/ordinary-csd-sub1.jpg",
        "/images/ordinary-csd-sub2.jpg",
      ],
    },
    {
      id: "36",
      title: "Lifestyle VI",
      category: "ordinary",
      type: "image",
      thumbnail: "/images/ordinary-ksw-main.jpg",
      year: "2026",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/ordinary-ksw-main.jpg",
        "/images/ordinary-ksw-sub1.jpg",
        "/images/ordinary-ksw-sub2.jpg",
      ],
    },
    {
      id: "22",
      title: "Summer II",
      category: "rostro",
      type: "image",
      thumbnail: "/images/rostro-cyj-main.jpg",
      year: "2025",
      description: "",
      aspectRatio: "portrait",
      images: [
        "/images/rostro-cyj-main.jpg",
        "/images/rostro-cyj-sub1.jpg",
        "/images/rostro-cyj-sub2.jpg",
      ],
    },
  ]

  export function getPortfolioItem(id: string): PortfolioItem | undefined {
    return portfolioItems.find((item) => item.id === id)
  }
